version: '3'
services:
  keycloak-auth-server:
    build:
      context: ./src/keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
