version: '3'
services:
  auth-server:
    build:
      context: auth-server-keycloak
      dockerfile: Dockerfile
    container_name: auth-server-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://auth-server

  auth-client-backend:
    build:
      context: auth-client-bff
      dockerfile: Dockerfile
    container_name: auth-bff-app
    ports:
      - "8081:8081"
    environment:
      DSN: "host=database port=5432 user=postgres password=password dbname=oauth sslmode=disable timezone=UTC connect_timeout=5"
      HOST: "http://auth-client-backend"
      KEYCLOAK_HOST: "http://auth-server:8080"
      FRONTEND_HOST: "http://auth-client-frontend:3000"
      PROTECTED_RESOURCE_HOST: "http://protected-resource:8082"
      CLIENT_ID: "billingApp"
      CLIENT_SECRET: "1ANIYGdYJhdeMjXOn6qrSmMU9wiUkXQ2"
    depends_on:
      - auth-server
      - database

  auth-client-frontend:
    build:
      context: auth-client-frontend
      dockerfile: Dockerfile
    container_name: auth-front-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_AUTH_CLIENT_URL: "http://auth-client-backend:8081"

  protected-resource:
    build:
      context: go-protected-resource
      dockerfile: Dockerfile
    container_name: auth-protected-resource
    ports:
      - "8082:8082"
    environment:
      KEYCLOAK_HOST: "http://auth-server:8080"

  database:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oauth
    volumes:
      - ./src/script/init.sql:/docker-entrypoint-initdb.d/init.sql
